apiVersion: apps/v1
kind: Deployment
metadata:
  name: images-api
  labels:
    app: images-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: images-api
  template:
    metadata:
      labels:
        app: images-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: doks.digitalocean.com/node-pool
                    operator: In
                    values:
                      - microservices-node-pool
      containers:
        - name: images-api
          image: greenstand/images-api:TAG
          ports:
            - containerPort: 80
#       imagePullSecrets:
#         - name: greenstand-docker-secret
